package br.com.integrado.view;

import br.com.integrado.dao.CadCidadeDao;
import br.com.integrado.dao.CadUfDao;
import br.com.integrado.enuns.Estados;
import br.com.integrado.model.CadCidade;
import br.com.integrado.model.CadUf;
import br.com.integrado.tools.ComboUtils;
import br.com.integrado.tools.DataUtils;
import br.com.integrado.tools.jTableUtils;
import br.com.integrado.view.consultas.ConsultaUF;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.event.WindowStateListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jsoliveira
 */
public class CadCidadeView extends javax.swing.JFrame {

    private Integer estado;
    private CadUfDao ufDao = new CadUfDao();
    private CadCidadeDao cDao = new CadCidadeDao();

    public CadCidadeView() {
        initComponents();

        this.estado = Estados.getPadrao().getEstado();

        ComboUtils.preencherCombo(jCBUf, ufDao.getAll());

        estadoPadraBotoes();

        habilitaCampos(false);

        jTableUtils.formatarJtable(jTable1, new int[]{40, 150, 200, 150});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBUf = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDataTransacao = new javax.swing.JTextField();
        jPnBotoes = new javax.swing.JPanel();
        jBtNovo = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtExcluir = new javax.swing.JButton();
        jBtGravar = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTfCodUf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTFNomeUf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTfSigla = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jCBTipoConsulta = new javax.swing.JComboBox<>();
        jTFValor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBTPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTfCodigo.setEnabled(false);

        jLabel1.setText("Código");

        jLabel2.setText("UF");

        jCBUf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Nome");

        jLabel4.setText("Data de Transação");

        jTFDataTransacao.setEnabled(false);

        jPnBotoes.setBackground(new java.awt.Color(204, 204, 204));

        jBtNovo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtNovo.setMnemonic('N');
        jBtNovo.setText("Novo");
        jBtNovo.setToolTipText("");
        jBtNovo.setPreferredSize(new java.awt.Dimension(85, 30));
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });
        jPnBotoes.add(jBtNovo);

        jBtAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtAlterar.setMnemonic('A');
        jBtAlterar.setText("Alterar");
        jBtAlterar.setPreferredSize(new java.awt.Dimension(85, 30));
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });
        jPnBotoes.add(jBtAlterar);

        jBtExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtExcluir.setMnemonic('E');
        jBtExcluir.setText("Excluir");
        jBtExcluir.setPreferredSize(new java.awt.Dimension(85, 30));
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });
        jPnBotoes.add(jBtExcluir);

        jBtGravar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtGravar.setMnemonic('G');
        jBtGravar.setText("Gravar");
        jBtGravar.setPreferredSize(new java.awt.Dimension(85, 30));
        jBtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtGravarActionPerformed(evt);
            }
        });
        jPnBotoes.add(jBtGravar);

        jBtCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtCancelar.setMnemonic('C');
        jBtCancelar.setText("Cancelar");
        jBtCancelar.setToolTipText("");
        jBtCancelar.setPreferredSize(new java.awt.Dimension(85, 30));
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });
        jPnBotoes.add(jBtCancelar);

        jLabel7.setText("Código");

        jTfCodUf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfCodUfFocusLost(evt);
            }
        });

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("UF");

        jTFNomeUf.setEnabled(false);

        jLabel9.setText("Sigla");

        jTfSigla.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jCBUf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 350, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTFDataTransacao))))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTfCodUf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTFNomeUf, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(186, 186, 186)
                                        .addComponent(jLabel9))))
                            .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDataTransacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTFNomeUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jPnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cidade", "UF", "Data de Transação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Tipo da Consulta");

        jCBTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Geral", "Por Código", "Cidade", "UF", " " }));

        jTFValor.setText("jTextField1");

        jLabel6.setText("Valor");

        jBTPesquisar.setMnemonic('P');
        jBTPesquisar.setText("Pesquisar");
        jBTPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBTPesquisar)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(636, 413));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
        estadoBotoes();
        habilitaCampos(true);
        limparCampos();
        this.estado = Estados.getInsercao().getEstado();

    }//GEN-LAST:event_jBtNovoActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        estadoBotoes();
        habilitaCampos(true);
        this.estado = Estados.getAlteracao().getEstado();

    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        estadoPadraBotoes();
        this.estado = Estados.getPadrao().getEstado();
        limparCampos();
        habilitaCampos(false);

    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jBtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtGravarActionPerformed

        try {
            CadCidade c = getCidade();
            if (c == null) {
                return;
            }

            if (this.estado == Estados.getInsercao().getEstado()) {
                cDao.insert(c);
                jTfCodigo.setText(c.getCdCidade().toString());
                JOptionPane.showMessageDialog(null, "Cidade salva com sucesso!!");
            }

            if (this.estado == Estados.getAlteracao().getEstado()) {

                cDao.update(c);
                JOptionPane.showMessageDialog(null, "Cidade alterada com sucesso!!");
            }

            jTFDataTransacao.setText(DataUtils.dateTimeToString(c.getDtTranscao()));
            estadoPadraBotoes();

            habilitaCampos(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar a cidade..:" + ex);
        }

    }//GEN-LAST:event_jBtGravarActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed

        try {

            CadCidade c = getCidade();
            if (c == null) {
                JOptionPane.showMessageDialog(null, "Selecione uma cidade para excluir");
                return;
            }

            if (JOptionPane.showConfirmDialog(null, "Deseja Excluir o Objeto", "Deseja Realment exlcuir a cidade?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.cDao.exclurir(c);
                JOptionPane.showMessageDialog(null, "Cidade excluída com sucesso!!!");
                limparCampos();
            }

        } catch (Exception ex) {

            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao excluir cidade");
        }

    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBTPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTPesquisarActionPerformed

        List<String> campos = new ArrayList<>();
        campos.add("CD_CIDADE");
        campos.add("NM_CIDADE");
        campos.add("NM_UF");
        campos.add("DT_TRANSACAO");

        switch (jCBTipoConsulta.getSelectedIndex()) {

            case 0: { //Geral
                jTableUtils.preencherJtable(jTable1, cDao.getAll(), campos);
            }
            break;
            case 1: {///Código

                try {

                    jTableUtils.preencherJtable(jTable1, cDao.getByCodigo(Long.parseLong(jTFValor.getText())), campos);

                } catch (Exception ex) {

                    JOptionPane.showMessageDialog(null, "Informe um valor numérico");
                }

            }
            break;
            case 2: { //Cidade
                jTableUtils.preencherJtable(jTable1, cDao.getByNmCidade(jTFValor.getText()), campos);
            }
            break;
            case 3: {///UF

                jTableUtils.preencherJtable(jTable1, cDao.getByNmUf(jTFValor.getText()), campos);
            }
            break;

        }

        cDao.fecharCursores();
    }//GEN-LAST:event_jBTPesquisarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        if (evt.getClickCount() > 1) {

            CadCidade c = cDao.getById(Long.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
            setCidade(c);
            jTabbedPane1.setSelectedIndex(0);

        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTfCodUfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfCodUfFocusLost

        if (jTfCodUf.getText().isEmpty()) {

            jTFNomeUf.setText("");
            jTfSigla.setText("");

            return;
        }

        try {

            Integer cdUf = Integer.parseInt(jTfCodUf.getText());
            CadUf uf = ufDao.getById(cdUf);

            if (uf == null) {
                JOptionPane.showMessageDialog(null, "Não foi localizada nenhum Unidade Federativa");
                jTfCodUf.setText("");
                jTFNomeUf.setText("");
                jTfSigla.setText("");

                return;
            }

            jTfCodUf.setText(uf.getCdUf().toString());
            jTFNomeUf.setText(uf.getNmUf());
            jTfSigla.setText(uf.getSgUf());

            jCBUf.setSelectedItem(uf);

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Informe um valor numérico");
            jTfCodUf.setText("");
            jTFNomeUf.setText("");
            jTfSigla.setText("");
            jTfCodUf.grabFocus();
            return;

        }


    }//GEN-LAST:event_jTfCodUfFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ConsultaUF con = new ConsultaUF(this, true);
        con.setVisible(true);

        con.addWindowListener(new WindowListener() {
            
            @Override
            public void windowOpened(WindowEvent we) {

            }

            @Override
            public void windowClosing(WindowEvent we) {

            }

            @Override
            public void windowClosed(WindowEvent we) {

                jTfCodUf.setText(con.codUf);
                jTfCodUfFocusLost(null);
            }

            @Override
            public void windowIconified(WindowEvent we) {

            }

            @Override
            public void windowDeiconified(WindowEvent we) {

            }

            @Override
            public void windowActivated(WindowEvent we) {

            }

            @Override
            public void windowDeactivated(WindowEvent we) {

            }
        });


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCidadeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCidadeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTPesquisar;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtGravar;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCBTipoConsulta;
    private javax.swing.JComboBox<String> jCBUf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPnBotoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDataTransacao;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFNomeUf;
    private javax.swing.JTextField jTFValor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTfCodUf;
    private javax.swing.JTextField jTfCodigo;
    private javax.swing.JTextField jTfSigla;
    // End of variables declaration//GEN-END:variables

    public CadCidade getCidade() {

        try {
            CadCidade c = new CadCidade();
            if (!jTfCodigo.getText().isEmpty()) {

                c.setCdCidade(Long.valueOf(jTfCodigo.getText()));
            }
            c.setUf((CadUf) jCBUf.getSelectedItem());

            if (jTFNome.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe um nome para a cidade");
                jTFNome.grabFocus();
                return null;
            }
            c.setNmCidade(jTFNome.getText());
            c.setDtTranscao(new Date());

            return c;
        } catch (Exception ex) {

            return null;
        }
    }

    public void setCidade(CadCidade cidade) {

        try {
            jTfCodigo.setText(cidade.getCdCidade().toString());
            jCBUf.setSelectedItem(cidade.getUf());
            jTFNome.setText(cidade.getNmCidade());
            jTFDataTransacao.setText(DataUtils.dateTimeToString(cidade.getDtTranscao()));
        } catch (Exception ex) {

            ex.printStackTrace();
        }

    }

    public void estadoPadraBotoes() {

        jBtNovo.setEnabled(true);
        jBtAlterar.setEnabled(true);
        jBtExcluir.setEnabled(true);

        jBtGravar.setEnabled(false);
        jBtCancelar.setEnabled(false);
    }

    public void estadoBotoes() {

        jBtNovo.setEnabled(false);
        jBtAlterar.setEnabled(false);
        jBtExcluir.setEnabled(false);

        jBtGravar.setEnabled(true);
        jBtCancelar.setEnabled(true);
    }

    public void habilitaCampos(boolean estado) {

        jTFNome.setEnabled(estado);
        jCBUf.setEditable(estado);

    }

    public void limparCampos() {

        jTFNome.setText("");
        jTfCodigo.setText("");
        jTFDataTransacao.setText("");
    }
}
